dist: jammy
language: node_js
node_js:
  - '20'

addons:
  chrome: stable

cache:
  directories:
    - ./node_modules

before_script:
  - export NODE_OPTIONS=–max_old_space_size=32000

install:
  - npm install --legacy-peer-deps

script:
  - npm run --max_old_space_size=32000 test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
